
export function texts() {
  return {
    en: {
      en: "En",
      SUBMIT: "Submit",
      REGISTRATION: "Registration",
      WE_NEVER_SHARE: "We'll never share your email with anyone else.",
      LOGOUT: "LogOut",
      LOGIN: "LogIn",
      HELLO: "Hello",
      GUEST: "guest",
      HOME: "Home",
      USERS: "Users",
      MY_DATA: "My Data",
      TRASH: "Trash",
      SETTIND: "Setting",
      DROP_HERE: "drop here",
      B: "B",
      KB: "KB",
      MB: "MB",
      GB: "GB",
      ALL: "All",
      CHOOSE_FILE: "Choose file",
      SORT: "Sort",
      NAME: "Name",
      DATE: "Date",
      CREATER: "Creater",
      SIZE: "Size",
      ASCENDING: "Ascending",
      DESCENDING: "Descending",
      VIEW: "View",
      TILES: "Tiles",
      DETAILS: "Details",
      DELETE: "Delete",
      RESTORE: "Restore",
      UP: "Up",
      NEW_FOLDER: "New folder",
      DELETE_MY_PROFILE: "Delete my profile from site",
      ARE_YOU_SURE_DELETE_PROFILE: "Are you sure you want to delete your profile?",
      ID: "Id",
      AC: "AC",
      NAME: "Name",
      EMAIL: "Email",
      PASSWORD: "Password",
      GROUP: "Group",
      EDIT: "Edit",
      DEL: "Del",
      ARE_YOU_SURE_DELETE_USER: "Are you sure you want to delete the",
      PASSWORD_CONFIRM: "Password Confirm",
      CANCEL: "Cancel",
      SUBMIT: "Sabmit",
      ACCESS: "Access",
      ADD_NEW_USER: "Add new user",
      WE_LL_NEVER_SHARE: "We'll never share your email with anyone else",

    },
    ru: {
      ru: "Рус",
      SUBMIT: "Отправить",
      REGISTRATION: "Регистрация",
      LOGOUT: "Выход",
      LOGIN: "Вход",
      HELLO: "Привет",
      GUEST: "гость",
      HOME: "Домашняя страница",
      USERS: "Пользователи",
      MY_DATA: "Мои данные",
      TRASH: "Корзина",
      SETTIND: "Настройки",
      DROP_HERE: "отпустите файлы",
      B: "Б",
      KB: "КБ",
      MB: "МБ",
      GB: "ГБ",
      ALL: "Все",
      CHOOSE_FILE: "Выбрать файлы",
      SORT: "Сортировка",
      NAME: "Имя",
      DATE: "Дата",
      CREATER: "Владелец",
      SIZE: "Размер",
      ASCENDING: "По возрастанию",
      DESCENDING: "По убыванию",
      VIEW: "Вид",
      TILES: "Крупные значки",
      DETAILS: "Таблица",
      DELETE: "Удалить",
      RESTORE: "Восстановить",
      UP: "Вверх",
      NEW_FOLDER: "Новая папка",
      DELETE_MY_PROFILE: "Удалить мою учетную запись с сайта",
      ARE_YOU_SURE_DELETE_PROFILE: "Вы уверены что хотите удалить свою учетную запись с сайта?",
      ID: "Id",
      AC: "Дос",
      NAME: "Имя",
      EMAIL: "Почта",
      PASSWORD: "Пароль",
      GROUP: "Группа",
      EDIT: "Прав",
      DEL: "Удал",
      ARE_YOU_SURE_DELETE_USER: "Вы уверены что хотите удалить пользователя",
      PASSWORD_CONFIRM: "Повторите пароль",
      CANCEL: "Отмена",
      SUBMIT: "Отправить",
      ACCESS: "Доступ",
      ADD_NEW_USER: "Добавить пользователя",
      WE_LL_NEVER_SHARE: "Мы никогда ни с кем не поделимся вашим почтовым адресом",
    }
  }
}